name: 'Lighthouse CI Slack Reporter'
description: 'Run Lighthouse tests on URLs and report results to Slack in tabular format'
author: 'MateuszMichalowski'
branding:
  icon: 'bar-chart-2'
  color: 'blue'

inputs:
  urls:
    description: 'Comma-separated list of URLs to test'
    required: true
  device_types:
    description: 'Device types to test (mobile, desktop, or both). Comma-separated. Defaults to all.'
    required: false
    default: 'mobile,desktop'
  categories:
    description: 'Test categories to run (performance, accessibility, best-practices, seo). Comma-separated. Defaults to all.'
    required: false
    default: 'performance,accessibility,best-practices,seo'
  slack_webhook_url:
    description: 'Slack Webhook URL to send reports to (required if slack_token is not provided)'
    required: false
  slack_channel:
    description: 'Slack channel to send the report to (without #)'
    required: false
  slack_token:
    description: 'Slack API token (required if slack_webhook_url is not provided)'
    required: false
  slack_title:
    description: 'Title for the Slack message'
    required: false
    default: 'Lighthouse Test Results'
  fail_on_score_below:
    description: 'Fail the action if any score is below this threshold (0-100)'
    required: false
    default: '0'
  chrome_flags:
    description: 'Custom Chrome flags for Lighthouse'
    required: false
    default: '--no-sandbox --headless --disable-gpu'
  timeout:
    description: 'Timeout for each test in seconds'
    required: false
    default: '60'
  slack_timeout_ms:
    description: 'Timeout for Slack API requests in milliseconds'
    required: false
    default: '10000'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Install required tools
      run: |
        npm install -g @vercel/ncc
        npm install -g typescript
      shell: bash

    - name: Build action
      run: npm run build
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run Lighthouse CI and report to Slack
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_URLS: ${{ inputs.urls }}
        INPUT_DEVICE_TYPES: ${{ inputs.device_types }}
        INPUT_CATEGORIES: ${{ inputs.categories }}
        INPUT_SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        INPUT_SLACK_CHANNEL: ${{ inputs.slack_channel }}
        INPUT_SLACK_TOKEN: ${{ inputs.slack_token }}
        INPUT_SLACK_TITLE: ${{ inputs.slack_title }}
        INPUT_FAIL_ON_SCORE_BELOW: ${{ inputs.fail_on_score_below }}
        INPUT_CHROME_FLAGS: ${{ inputs.chrome_flags }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_SLACK_TIMEOUT_MS: ${{ inputs.slack_timeout_ms }}
