name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint and build
        run: npm run all

      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.6.2
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            # Lighthouse CI Slack Reporter ${{ github.ref_name }}
            
            ## Changes
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation
            
            ```yaml
            - uses: MateuszMichalowski/lhci-slack-reporter@${{ github.ref_name }}
            ```
            
            ## Documentation
            For full documentation, see the [README](https://github.com/MateuszMichalowski/lhci-slack-reporter/blob/main/README.md)
          files: |
            dist/index.js
            LICENSE
            README.md
          draft: false
