name: Test Lighthouse Action

on:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Lighthouse CI Slack Reporter
        uses: ./
        with:
          urls: 'https://monterial.com'
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          
