name: Test Lighthouse CI Slack Reporter

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
  
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Lighthouse tests (self-test)
        uses: ./
        with:
          urls: 'https://monterail.com/,https://monterail.com/services/'
          device_types: 'mobile'
          categories: 'performance,accessibility'
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_title: 'Self-Test Results'
          timeout: '45'

      - name: Check if dist/index.js exists
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "::error::dist/index.js not found. Build failed."
            exit 1
          fi
          echo "✅ Build artifacts verified"
